//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowCustomers")]
        public string ConsoleApp1_WebService_workflowCustomers_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowCustomers_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/salesDocuments")]
        public string ConsoleApp1_WebService_salesDocuments_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_salesDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_Aged_Acc_Receivable")]
        public string ConsoleApp1_WebService_Power_BI_Aged_Acc_Receivable_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_Aged_Acc_Receivable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/ExcelTemplateCashFlowStatement")]
        public string ConsoleApp1_WebService_ExcelTemplateCashFlowStatement_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_ExcelTemplateCashFlowStatement_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/SystemService")]
        public string ConsoleApp1_WebService_SystemService {
            get {
                return ((string)(this["ConsoleApp1_WebService_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowPurchaseDocuments")]
        public string ConsoleApp1_WebService_workflowPurchaseDocuments_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowPurchaseDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/salesDocumentLines")]
        public string ConsoleApp1_WebService_salesDocumentLines_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_salesDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_Sales_Pipeline")]
        public string ConsoleApp1_WebService_Power_BI_Sales_Pipeline_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_Sales_Pipeline_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/purchaseDocuments")]
        public string ConsoleApp1_WebService_purchaseDocuments_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_purchaseDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_Top_5_Opportunities")]
        public string ConsoleApp1_WebService_Power_BI_Top_5_Opportunities_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_Top_5_Opportunities_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowVendors")]
        public string ConsoleApp1_WebService_workflowVendors_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowVendors_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_Job_Act_v_Budg_Cost")]
        public string ConsoleApp1_WebService_Power_BI_Job_Act_v_Budg_Cost_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_Job_Act_v_Budg_Cost_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/ExcelTemplateAgedAccountsReceivable")]
        public string ConsoleApp1_WebService_ExcelTemplateAgedAccountsReceivable_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_ExcelTemplateAgedAccountsReceivable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/purchaseDocumentLines")]
        public string ConsoleApp1_WebService_purchaseDocumentLines_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_purchaseDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Job_List")]
        public string ConsoleApp1_WebService_Job_List_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Job_List_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/ExcelTemplateIncomeStatement")]
        public string ConsoleApp1_WebService_ExcelTemplateIncomeStatement_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_ExcelTemplateIncomeStatement_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowGenJournalBatches")]
        public string ConsoleApp1_WebService_workflowGenJournalBatches_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowGenJournalBatches_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Cod" +
            "eunit/Letters")]
        public string ConsoleApp1_WebService_Letters {
            get {
                return ((string)(this["ConsoleApp1_WebService_Letters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/AccountantPortalFinanceCues")]
        public string ConsoleApp1_WebService_AccountantPortalFinanceCues_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_AccountantPortalFinanceCues_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/SalesOrder")]
        public string ConsoleApp1_WebService_SalesOrder_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_SalesOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/powerbifinance")]
        public string ConsoleApp1_WebService_powerbifinance_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_powerbifinance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_Aged_Acc_Payable")]
        public string ConsoleApp1_WebService_Power_BI_Aged_Acc_Payable_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_Aged_Acc_Payable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_Job_Profitability")]
        public string ConsoleApp1_WebService_Power_BI_Job_Profitability_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_Job_Profitability_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Cod" +
            "eunit/WorkflowActionResponse")]
        public string ConsoleApp1_WebService_WorkflowActionResponse {
            get {
                return ((string)(this["ConsoleApp1_WebService_WorkflowActionResponse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/ExcelTemplateTrialBalance")]
        public string ConsoleApp1_WebService_ExcelTemplateTrialBalance_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_ExcelTemplateTrialBalance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowWebhookSubscriptions")]
        public string ConsoleApp1_WebService_workflowWebhookSubscriptions_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowWebhookSubscriptions_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowSalesDocuments")]
        public string ConsoleApp1_WebService_workflowSalesDocuments_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowSalesDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/AccountantPortalUserTasks")]
        public string ConsoleApp1_WebService_AccountantPortalUserTasks_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_AccountantPortalUserTasks_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_Job_Act_v_Budg_Price")]
        public string ConsoleApp1_WebService_Power_BI_Job_Act_v_Budg_Price_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_Job_Act_v_Budg_Price_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowSalesDocumentLines")]
        public string ConsoleApp1_WebService_workflowSalesDocumentLines_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowSalesDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_WorkDate_Calc")]
        public string ConsoleApp1_WebService_Power_BI_WorkDate_Calc_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_WorkDate_Calc_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Fields")]
        public string ConsoleApp1_WebService_Fields_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Fields_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/ExcelTemplateRetainedEarnings")]
        public string ConsoleApp1_WebService_ExcelTemplateRetainedEarnings_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_ExcelTemplateRetainedEarnings_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowGenJournalLines")]
        public string ConsoleApp1_WebService_workflowGenJournalLines_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowGenJournalLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/ExcelTemplateAgedAccountsPayable")]
        public string ConsoleApp1_WebService_ExcelTemplateAgedAccountsPayable_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_ExcelTemplateAgedAccountsPayable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/ExcelTemplateBalanceSheet")]
        public string ConsoleApp1_WebService_ExcelTemplateBalanceSheet_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_ExcelTemplateBalanceSheet_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/miniforms")]
        public string ConsoleApp1_WebService_miniforms_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_miniforms_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Job_Task_Lines")]
        public string ConsoleApp1_WebService_Job_Task_Lines_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Job_Task_Lines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Power_BI_Aged_Inventory_Chart")]
        public string ConsoleApp1_WebService_Power_BI_Aged_Inventory_Chart_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Power_BI_Aged_Inventory_Chart_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Chart_of_Accounts")]
        public string ConsoleApp1_WebService_Chart_of_Accounts_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Chart_of_Accounts_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/Job_Planning_Lines")]
        public string ConsoleApp1_WebService_Job_Planning_Lines_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_Job_Planning_Lines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/ExcelTemplateViewCompanyInformation")]
        public string ConsoleApp1_WebService_ExcelTemplateViewCompanyInformation_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_ExcelTemplateViewCompanyInformation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/UserTaskSetComplete")]
        public string ConsoleApp1_WebService_UserTaskSetComplete_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_UserTaskSetComplete_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowPurchaseDocumentLines")]
        public string ConsoleApp1_WebService_workflowPurchaseDocumentLines_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowPurchaseDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/workflowItems")]
        public string ConsoleApp1_WebService_workflowItems_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_workflowItems_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7647/DynamicsNAV110/WS/ReplaceWithAPercentEncodedCompanyName/Pag" +
            "e/AccountantPortalActivityCues")]
        public string ConsoleApp1_WebService_AccountantPortalActivityCues_Service {
            get {
                return ((string)(this["ConsoleApp1_WebService_AccountantPortalActivityCues_Service"]));
            }
        }
    }
}
