//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Letters", ConfigurationName="ServiceReference1.Letters_Port")]
    public interface Letters_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Capitalize_Result) of message Capitalize_Result does not match the default value (Capitalize)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Letters:Capitalize", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.Capitalize_Result Capitalize(ConsoleApp1.ServiceReference1.Capitalize request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Letters:Capitalize", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.Capitalize_Result> CapitalizeAsync(ConsoleApp1.ServiceReference1.Capitalize request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Capitalize", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Letters", IsWrapped=true)]
    public partial class Capitalize {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Letters", Order=0)]
        public string paramInput;
        
        public Capitalize() {
        }
        
        public Capitalize(string paramInput) {
            this.paramInput = paramInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Capitalize_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Letters", IsWrapped=true)]
    public partial class Capitalize_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Letters", Order=0)]
        public string return_value;
        
        public Capitalize_Result() {
        }
        
        public Capitalize_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Letters_PortChannel : ConsoleApp1.ServiceReference1.Letters_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Letters_PortClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.Letters_Port>, ConsoleApp1.ServiceReference1.Letters_Port {
        
        public Letters_PortClient() {
        }
        
        public Letters_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Letters_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Letters_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Letters_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.Capitalize_Result ConsoleApp1.ServiceReference1.Letters_Port.Capitalize(ConsoleApp1.ServiceReference1.Capitalize request) {
            return base.Channel.Capitalize(request);
        }
        
        public string Capitalize(string paramInput) {
            ConsoleApp1.ServiceReference1.Capitalize inValue = new ConsoleApp1.ServiceReference1.Capitalize();
            inValue.paramInput = paramInput;
            ConsoleApp1.ServiceReference1.Capitalize_Result retVal = ((ConsoleApp1.ServiceReference1.Letters_Port)(this)).Capitalize(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.Capitalize_Result> ConsoleApp1.ServiceReference1.Letters_Port.CapitalizeAsync(ConsoleApp1.ServiceReference1.Capitalize request) {
            return base.Channel.CapitalizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.Capitalize_Result> CapitalizeAsync(string paramInput) {
            ConsoleApp1.ServiceReference1.Capitalize inValue = new ConsoleApp1.ServiceReference1.Capitalize();
            inValue.paramInput = paramInput;
            return ((ConsoleApp1.ServiceReference1.Letters_Port)(this)).CapitalizeAsync(inValue);
        }
    }
}
